apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weather-app

resources:
  - ../../base

nameSuffix: -green

patches:
  - patch: |-
      - op: replace
        path: /spec/template/metadata/labels/slot
        value: green
      - op: replace
        path: /metadata/name
        value: weather-app-green
    target:
      kind: Deployment
      name: weather-app

images:
  - name: ghcr.io/avadhutpatil22/weather-app
    newTag: "green"   # candidate release — green slot
