server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /slot {
        default_type text/plain;
        return 200 "$hostname";
    }
}
