apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-app-blue
  namespace: argocd
spec:
  project: weather-project

  source:
    repoURL: https://github.com/YOUR_USERNAME/weather-app-gitops.git
    targetRevision: HEAD
    path: manifests/overlays/blue

  destination:
    server: https://kubernetes.default.svc
    namespace: weather-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
