apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weather-app

resources:
  - ../../base

nameSuffix: -green

commonLabels:
  slot: green

patches:
  - target:
      kind: Deployment
      name: weather-app
    patch: |-
      - op: replace
        path: /spec/template/metadata/labels/app
        value: weather-app-green

      - op: replace
        path: /spec/selector/matchLabels/app
        value: weather-app-green

      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/avadhutpatil22/weather-app:v2

  - target:
      kind: Service
      name: weather-app-active
    patch: |-
      - op: replace
        path: /spec/selector/app
        value: weather-app-green

  - target:
      kind: Service
      name: weather-app-preview
    patch: |-
      - op: replace
        path: /spec/selector/app
        value: weather-app-green
