apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: weather-project
  namespace: argocd
spec:
  description: Weather App GitOps Project

  sourceRepos:
    - '*'

  destinations:
    - namespace: weather-app
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
