```yaml id="3bpvdo"
name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        run: |
          docker build \
          -t ghcr.io/${{ github.repository_owner }}/weather-app:v${{ github.run_number }} .

      - name: Push Image
        run: |
          docker push \
          ghcr.io/${{ github.repository_owner }}/weather-app:v${{ github.run_number }}
